/* Generated By:JJTree: Do not edit this line. ASTattr_list.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mieic.comp.parsing;

public
class ASTattr_list extends SimpleNode {
  public ASTattr_list(int id) {
    super(id);
  }

  public ASTattr_list(Dot2DotParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3c50340e6b65a7c8977233869e2b0d49 (do not edit this line) */
