/* Generated By:JJTree: Do not edit this line. ASTa_list.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mieic.comp.parsing;

public
class ASTa_list extends SimpleNode {
  public ASTa_list(int id) {
    super(id);
  }

  public ASTa_list(Dot2DotParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5281f43ebe68ef7b67c51c97d16e74c4 (do not edit this line) */
