/* Generated By:JJTree: Do not edit this line. ASTattr_stmt.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mieic.comp.parsing;

public
class ASTattr_stmt extends SimpleNode {
  public ASTattr_stmt(int id) {
    super(id);
  }

  public ASTattr_stmt(Dot2DotParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3496ec7cf94b08272566e2ca2aa5abf4 (do not edit this line) */
