/* Generated By:JJTree: Do not edit this line. ASTa_list_aux.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mieic.comp.parsing;

public
class ASTa_list_aux extends SimpleNode {
  public ASTa_list_aux(int id) {
    super(id);
  }

  public ASTa_list_aux(Dot2DotParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=59ef3210106a90dbee4d68902057cf5e (do not edit this line) */
