/* Generated By:JJTree: Do not edit this line. ASTedge_stmt.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mieic.comp.parsing;

public
class ASTedge_stmt extends SimpleNode {
  public ASTedge_stmt(int id) {
    super(id);
  }

  public ASTedge_stmt(Dot2DotParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1d3c1863c92e00beda2356b36ba65359 (do not edit this line) */
