/* Generated By:JJTree: Do not edit this line. ASTedgeRHS.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mieic.comp.parsing;

public
class ASTedgeRHS extends SimpleNode {
  public ASTedgeRHS(int id) {
    super(id);
  }

  public ASTedgeRHS(Dot2DotParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=41549e602cbfe9c08984a330579d8a2a (do not edit this line) */
