/* Generated By:JJTree: Do not edit this line. ASTgraph.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mieic.comp.parsing;

public
class ASTgraph extends SimpleNode {
  public ASTgraph(int id) {
    super(id);
  }

  public ASTgraph(Dot2DotParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d657dc8bddbcd7c7d85e4ec1170a47ed (do not edit this line) */
