/* Generated By:JJTree: Do not edit this line. ASTnode_id.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mieic.comp.parsing;

public
class ASTnode_id extends SimpleNode {
  public ASTnode_id(int id) {
    super(id);
  }

  public ASTnode_id(Dot2DotParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d14cfbc69b6c88a730b147e042b1690f (do not edit this line) */
