/* Generated By:JJTree: Do not edit this line. ASTnode_stmt.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mieic.comp.parsing;

public
class ASTnode_stmt extends SimpleNode {
  public ASTnode_stmt(int id) {
    super(id);
  }

  public ASTnode_stmt(Dot2DotParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d0b17dcee511e3194dd54f897e47cd01 (do not edit this line) */
