/* Generated By:JJTree: Do not edit this line. ASTport.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mieic.comp.parsing;

public
class ASTport extends SimpleNode {
  public ASTport(int id) {
    super(id);
  }

  public ASTport(Dot2DotParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b32f29e687bc3eada9c19dea6acba048 (do not edit this line) */
