/* Generated By:JJTree: Do not edit this line. ASTsubgraph.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mieic.comp.parsing;

public
class ASTsubgraph extends SimpleNode {
  public ASTsubgraph(int id) {
    super(id);
  }

  public ASTsubgraph(Dot2DotParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=12421c692ef498eaa074f653077d3307 (do not edit this line) */
