/* Generated By:JJTree: Do not edit this line. ASTstmt_list.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mieic.comp.parsing;

public
class ASTstmt_list extends SimpleNode {
  public ASTstmt_list(int id) {
    super(id);
  }

  public ASTstmt_list(Dot2DotParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0bb5bf838a8ec8e978166795a571e182 (do not edit this line) */
