/* Generated By:JJTree: Do not edit this line. ASTstmt.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mieic.comp.parsing;

public
class ASTstmt extends SimpleNode {
  public ASTstmt(int id) {
    super(id);
  }

  public ASTstmt(Dot2DotParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=06221c746a645c15ed6ab6c7b1cd95e8 (do not edit this line) */
