/* Generated By:JavaCC: Do not edit this line. Dot2DotParserTreeConstants.java Version 5.0 */
package mieic.comp.parsing;

public interface Dot2DotParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTGRAPH = 1;
  public int JJTSTMT_LIST = 2;
  public int JJTSTMT = 3;
  public int JJTNODE_STMT = 4;
  public int JJTNODE_ID = 5;
  public int JJTPORT = 6;
  public int JJTATTR_LIST = 7;
  public int JJTA_LIST = 8;
  public int JJTA_LIST_AUX = 9;
  public int JJTEDGE_STMT = 10;
  public int JJTEDGERHS = 11;
  public int JJTATTR_STMT = 12;
  public int JJTSUBGRAPH = 13;


  public String[] jjtNodeName = {
    "Start",
    "graph",
    "stmt_list",
    "stmt",
    "node_stmt",
    "node_id",
    "port",
    "attr_list",
    "a_list",
    "a_list_aux",
    "edge_stmt",
    "edgeRHS",
    "attr_stmt",
    "subgraph",
  };
}
/* JavaCC - OriginalChecksum=552189705394c1d0463566091f11f2ed (do not edit this line) */
