/* Generated By:JavaCC: Do not edit this line. Dot2DotParserTreeConstants.java Version 5.0 */
package mieic.comp.parsing;

public interface Dot2DotParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;


  public String[] jjtNodeName = {
    "Start",
    "void",
  };
}
/* JavaCC - OriginalChecksum=a3968e2f6c6844d58b984f51edf19a04 (do not edit this line) */
