/* Generated By:JJTree&JavaCC: Do not edit this line. Dot2DotParserConstants.java */
package mieic.comp.parsing;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Dot2DotParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int STRICT = 7;
  /** RegularExpression Id. */
  int GRAPH = 8;
  /** RegularExpression Id. */
  int DIGRAPH = 9;
  /** RegularExpression Id. */
  int NODE = 10;
  /** RegularExpression Id. */
  int EDGE = 11;
  /** RegularExpression Id. */
  int SUBGRAPH = 12;
  /** RegularExpression Id. */
  int DIRECTION = 13;
  /** RegularExpression Id. */
  int EDGEOP = 14;
  /** RegularExpression Id. */
  int ID = 15;
  /** RegularExpression Id. */
  int LETTER = 16;
  /** RegularExpression Id. */
  int DIGIT = 17;
  /** RegularExpression Id. */
  int STRING = 18;
  /** RegularExpression Id. */
  int HTML = 19;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<STRICT>",
    "<GRAPH>",
    "<DIGRAPH>",
    "<NODE>",
    "<EDGE>",
    "<SUBGRAPH>",
    "<DIRECTION>",
    "<EDGEOP>",
    "<ID>",
    "<LETTER>",
    "<DIGIT>",
    "<STRING>",
    "<HTML>",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\":\"",
    "\"[\"",
    "\"]\"",
    "\"=\"",
    "\",\"",
  };

}
