/* Generated By:JJTree: Do not edit this line. ASTAssignStmt.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mieic.comp.parser;

public
class ASTAssignStmt extends SimpleNode {
  public ASTAssignStmt(int id) {
    super(id);
  }

  public ASTAssignStmt(Dot2DotParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=011af0b095106eda959e3563417dbf4e (do not edit this line) */
