/* Generated By:JJTree: Do not edit this line. ASTDigraph.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mieic.comp.parser;

public
class ASTDigraph extends ASTGraph {
  public ASTDigraph(int id) {
    super(id);
  }

  public ASTDigraph(Dot2DotParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ea90b2c78cc948fc20580dc53c3c2bb7 (do not edit this line) */
