/* Generated By:JJTree: Do not edit this line. ASTNodeInfo.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mieic.comp.parser;

public
class ASTNodeInfo extends SimpleNode {
  public ASTNodeInfo(int id) {
    super(id);
  }

  public ASTNodeInfo(Dot2DotParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5a04d22a531fbece5f59c685cf79e118 (do not edit this line) */
