/* Generated By:JJTree: Do not edit this line. ASTPort.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mieic.comp.parser;

public class ASTPort extends SimpleNode {

	private String portId;
	private String portDir;

	public ASTPort(int id) {
		super(id);
	}

	public ASTPort(Dot2DotParser p, int id) {
		super(p, id);
	}

	public void setPort(String portId, String direction) {
		this.portId = portId;
		portDir = direction;
	}

	public void setPort(String direction) {
		portDir = direction;
	}
}
/*
 * JavaCC - OriginalChecksum=6dc7aeae683e3f487c439217f50e66e1 (do not edit this
 * line)
 */
