/* Generated By:JJTree: Do not edit this line. ASTSubgraph.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mieic.comp.parser;

public
class ASTSubgraph extends ASTGraph {
  public ASTSubgraph(int id) {
    super(id);
  }

  public ASTSubgraph(Dot2DotParser p, int id) {
    super(p, id);
  }
}
/* JavaCC - OriginalChecksum=6365c108b5d70b76d06f5f96e859225a (do not edit this line) */
