/* Generated By:JJTree&JavaCC: Do not edit this line. Dot2DotParser.java */
package mieic.comp.parser;
import java.io.*;

public class Dot2DotParser/*@bgen(jjtree)*/implements Dot2DotParserTreeConstants, Dot2DotParserConstants {/*@bgen(jjtree)*/
  protected JJTDot2DotParserState jjtree = new JJTDot2DotParserState();public static boolean parse(String args [])
  {
    Dot2DotParser parser = null;
    if (args.length == 0)
    {
      System.out.println("Dot2Dot:  Reading from standard input . . .");
      parser = new Dot2DotParser(System.in);
    }
    else if (args.length == 1)
    {
      System.out.println("Dot2Dot:  Reading from file " + args [0] + " . . .");
      try
      {
        parser = new Dot2DotParser(new java.io.FileInputStream(args [0]));
      }
      catch (java.io.FileNotFoundException e)
      {
        System.out.println("Java Parser Version 1.1:  File " + args [0] + " not found.");
        return false;
      }
    }
    else
    {
      System.out.println("Dot2Dot:  Usage is one of:");
      System.out.println("         java dot2dot < inputfile");
      System.out.println("OR");
      System.out.println("         java dot2dot inputfile");
      return false;
    }
    try
    {
      SimpleNode root = parser.Start();
      root.dump("");
      return true;
    }
    catch (ParseException e)
    {
      System.out.println(e.getMessage());
      System.out.println("Dot2Dot:  Encountered errors during parse.");
      return false;
    }
  }

  final public SimpleNode Start() throws ParseException {
 /*@bgen(jjtree) Start */
  ASTStart jjtn000 = new ASTStart(JJTSTART);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      graph();
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    {if (true) return jjtn000;}
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

  final public void graph() throws ParseException {
 /*@bgen(jjtree) Graph */
  ASTGraph jjtn000 = new ASTGraph(JJTGRAPH);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token t1 = null, t2, t3;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case STRICT:
        t1 = jj_consume_token(STRICT);
        break;
      default:
        jj_la1[0] = jj_gen;
        ;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case GRAPH:
        t2 = jj_consume_token(GRAPH);
        break;
      case DIGRAPH:
        t2 = jj_consume_token(DIGRAPH);
        break;
      default:
        jj_la1[1] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ID:
        t3 = jj_consume_token(ID);
      if (t1 != null && t1.image.toLowerCase().equals("strict"))
      {
        jjtn000.setStrictness(true);
      }
      switch (t2.image.toLowerCase())
      {
        case "graph" : jjtn000.setGraphType(ASTGraph.graphType.GRAPH);
        break;
        case "digraph" : jjtn000.setGraphType(ASTGraph.graphType.DIGRAPH);
        break;
      }
      jjtn000.setId(t3.image);
        break;
      default:
        jj_la1[2] = jj_gen;
        ;
      }
      jj_consume_token(23);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case GRAPH:
      case NODE:
      case EDGE:
      case SUBGRAPH:
      case ID:
      case 23:
        stmt_list();
        break;
      default:
        jj_la1[3] = jj_gen;
        ;
      }
      jj_consume_token(24);
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  final public void stmt_list() throws ParseException {
    stmt();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 25:
      jj_consume_token(25);
      break;
    default:
      jj_la1[4] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case GRAPH:
    case NODE:
    case EDGE:
    case SUBGRAPH:
    case ID:
    case 23:
      stmt_list();
      break;
    default:
      jj_la1[5] = jj_gen;
      ;
    }
  }

  final public void stmt() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case GRAPH:
    case NODE:
    case EDGE:
    ASTAttrStmt jjtn001 = new ASTAttrStmt(JJTATTRSTMT);
    boolean jjtc001 = true;
    jjtree.openNodeScope(jjtn001);
      try {
        attr_stmt();
      } catch (Throwable jjte001) {
    if (jjtc001) {
      jjtree.clearNodeScope(jjtn001);
      jjtc001 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte001 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte001;}
    }
    if (jjte001 instanceof ParseException) {
      {if (true) throw (ParseException)jjte001;}
    }
    {if (true) throw (Error)jjte001;}
      } finally {
    if (jjtc001) {
      jjtree.closeNodeScope(jjtn001, true);
    }
      }
      break;
    case ID:
      simple_node_id();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case EDGEOP:
    ASTEdgeStmt jjtn002 = new ASTEdgeStmt(JJTEDGESTMT);
    boolean jjtc002 = true;
    jjtree.openNodeScope(jjtn002);
        try {
          edge_stmt();
        } catch (Throwable jjte002) {
    if (jjtc002) {
      jjtree.clearNodeScope(jjtn002);
      jjtc002 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte002 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte002;}
    }
    if (jjte002 instanceof ParseException) {
      {if (true) throw (ParseException)jjte002;}
    }
    {if (true) throw (Error)jjte002;}
        } finally {
    if (jjtc002) {
      jjtree.closeNodeScope(jjtn002, true);
    }
        }
        break;
      case 26:
        jj_consume_token(26);
        ASTAssignStmt jjtn003 = new ASTAssignStmt(JJTASSIGNSTMT);
        boolean jjtc003 = true;
        jjtree.openNodeScope(jjtn003);
        try {
          simple_node_id();
        } catch (Throwable jjte003) {
        if (jjtc003) {
          jjtree.clearNodeScope(jjtn003);
          jjtc003 = false;
        } else {
          jjtree.popNode();
        }
        if (jjte003 instanceof RuntimeException) {
          {if (true) throw (RuntimeException)jjte003;}
        }
        if (jjte003 instanceof ParseException) {
          {if (true) throw (ParseException)jjte003;}
        }
        {if (true) throw (Error)jjte003;}
        } finally {
        if (jjtc003) {
          jjtree.closeNodeScope(jjtn003, true);
        }
        }
        break;
      default:
        jj_la1[6] = jj_gen;
    ASTNodeStmt jjtn004 = new ASTNodeStmt(JJTNODESTMT);
    boolean jjtc004 = true;
    jjtree.openNodeScope(jjtn004);
        try {
          node_stmt();
        } catch (Throwable jjte004) {
    if (jjtc004) {
      jjtree.clearNodeScope(jjtn004);
      jjtc004 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte004 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte004;}
    }
    if (jjte004 instanceof ParseException) {
      {if (true) throw (ParseException)jjte004;}
    }
    {if (true) throw (Error)jjte004;}
        } finally {
    if (jjtc004) {
      jjtree.closeNodeScope(jjtn004, true);
    }
        }
      }
      break;
    case SUBGRAPH:
    case 23:
  ASTSubgraph jjtn005 = new ASTSubgraph(JJTSUBGRAPH);
  boolean jjtc005 = true;
  jjtree.openNodeScope(jjtn005);
      try {
        subgraph();
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case EDGEOP:
          edge_stmt();
          break;
        default:
          jj_la1[7] = jj_gen;
          ;
        }
      } catch (Throwable jjte005) {
  if (jjtc005) {
    jjtree.clearNodeScope(jjtn005);
    jjtc005 = false;
  } else {
    jjtree.popNode();
  }
  if (jjte005 instanceof RuntimeException) {
    {if (true) throw (RuntimeException)jjte005;}
  }
  if (jjte005 instanceof ParseException) {
    {if (true) throw (ParseException)jjte005;}
  }
  {if (true) throw (Error)jjte005;}
      } finally {
  if (jjtc005) {
    jjtree.closeNodeScope(jjtn005, true);
  }
      }
      break;
    default:
      jj_la1[8] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void simple_node_id() throws ParseException {
 /*@bgen(jjtree) NodeStmt */
 ASTNodeStmt jjtn000 = new ASTNodeStmt(JJTNODESTMT);
 boolean jjtc000 = true;
 jjtree.openNodeScope(jjtn000);Token t1;
    try {
      t1 = jj_consume_token(ID);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    jjtn000.setNodeId(t1.image);
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  final public void node_stmt() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 27:
      port();
      break;
    default:
      jj_la1[9] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 28:
      attr_list();
      break;
    default:
      jj_la1[10] = jj_gen;
      ;
    }
  }

  final public void node_id() throws ParseException {
    jj_consume_token(ID);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 27:
      port();
      break;
    default:
      jj_la1[11] = jj_gen;
      ;
    }
  }

  final public void port() throws ParseException {
    jj_consume_token(27);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ID:
      jj_consume_token(ID);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 27:
        jj_consume_token(27);
        jj_consume_token(DIRECTION);
        break;
      default:
        jj_la1[12] = jj_gen;
        ;
      }
      break;
    case DIRECTION:
      jj_consume_token(DIRECTION);
      break;
    default:
      jj_la1[13] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void attr_list() throws ParseException {
    jj_consume_token(28);
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ID:
        ;
        break;
      default:
        jj_la1[14] = jj_gen;
        break label_1;
      }
      ASTAttribute jjtn001 = new ASTAttribute(JJTATTRIBUTE);
      boolean jjtc001 = true;
      jjtree.openNodeScope(jjtn001);
      try {
        attribute();
      } catch (Throwable jjte001) {
      if (jjtc001) {
        jjtree.clearNodeScope(jjtn001);
        jjtc001 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte001 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte001;}
      }
      if (jjte001 instanceof ParseException) {
        {if (true) throw (ParseException)jjte001;}
      }
      {if (true) throw (Error)jjte001;}
      } finally {
      if (jjtc001) {
        jjtree.closeNodeScope(jjtn001, true);
      }
      }
    }
    jj_consume_token(29);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 28:
      attr_list();
      break;
    default:
      jj_la1[15] = jj_gen;
      ;
    }
  }

  final public void attribute() throws ParseException {
    jj_consume_token(ID);
    jj_consume_token(26);
    jj_consume_token(ID);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 25:
    case 30:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 25:
        jj_consume_token(25);
        break;
      case 30:
        jj_consume_token(30);
        break;
      default:
        jj_la1[16] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[17] = jj_gen;
      ;
    }
  }

  final public void edge_stmt() throws ParseException {
    edgeRHS();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 28:
      attr_list();
      break;
    default:
      jj_la1[18] = jj_gen;
      ;
    }
  }

  final public void edgeRHS() throws ParseException {
    jj_consume_token(EDGEOP);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ID:
      ASTNodeStmt jjtn001 = new ASTNodeStmt(JJTNODESTMT);
      boolean jjtc001 = true;
      jjtree.openNodeScope(jjtn001);
      try {
        node_id();
      } catch (Throwable jjte001) {
      if (jjtc001) {
        jjtree.clearNodeScope(jjtn001);
        jjtc001 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte001 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte001;}
      }
      if (jjte001 instanceof ParseException) {
        {if (true) throw (ParseException)jjte001;}
      }
      {if (true) throw (Error)jjte001;}
      } finally {
      if (jjtc001) {
        jjtree.closeNodeScope(jjtn001, true);
      }
      }
      break;
    case SUBGRAPH:
    case 23:
      ASTSubgraph jjtn002 = new ASTSubgraph(JJTSUBGRAPH);
      boolean jjtc002 = true;
      jjtree.openNodeScope(jjtn002);
      try {
        subgraph();
      } catch (Throwable jjte002) {
      if (jjtc002) {
        jjtree.clearNodeScope(jjtn002);
        jjtc002 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte002 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte002;}
      }
      if (jjte002 instanceof ParseException) {
        {if (true) throw (ParseException)jjte002;}
      }
      {if (true) throw (Error)jjte002;}
      } finally {
      if (jjtc002) {
        jjtree.closeNodeScope(jjtn002, true);
      }
      }
      break;
    default:
      jj_la1[19] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case EDGEOP:
    ASTEdgeStmt jjtn003 = new ASTEdgeStmt(JJTEDGESTMT);
    boolean jjtc003 = true;
    jjtree.openNodeScope(jjtn003);
      try {
        edgeRHS();
      } catch (Throwable jjte003) {
    if (jjtc003) {
      jjtree.clearNodeScope(jjtn003);
      jjtc003 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte003 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte003;}
    }
    if (jjte003 instanceof ParseException) {
      {if (true) throw (ParseException)jjte003;}
    }
    {if (true) throw (Error)jjte003;}
      } finally {
    if (jjtc003) {
      jjtree.closeNodeScope(jjtn003, true);
    }
      }
      break;
    default:
      jj_la1[20] = jj_gen;
      ;
    }
  }

  final public void attr_stmt() throws ParseException {
 Token t1;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case GRAPH:
      t1 = jj_consume_token(GRAPH);
      attr_list();
      break;
    case NODE:
      t1 = jj_consume_token(NODE);
      attr_list();
      break;
    case EDGE:
      t1 = jj_consume_token(EDGE);
      attr_list();
   switch(t1.image.toLowerCase())
   {
        case "graph":
        break;
        case "node":
        break;
        case "edge":
        break;
   }
      break;
    default:
      jj_la1[21] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void subgraph() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case SUBGRAPH:
      jj_consume_token(SUBGRAPH);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ID:
        jj_consume_token(ID);
        break;
      default:
        jj_la1[22] = jj_gen;
        ;
      }
      break;
    default:
      jj_la1[23] = jj_gen;
      ;
    }
    jj_consume_token(23);
    stmt_list();
    jj_consume_token(24);
  }

  /** Generated Token Manager. */
  public Dot2DotParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[24];
  static private int[] jj_la1_0;
  static {
      jj_la1_init_0();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x200,0xc00,0x20000,0x827400,0x2000000,0x827400,0x4010000,0x10000,0x827400,0x8000000,0x10000000,0x8000000,0x8000000,0x28000,0x20000,0x10000000,0x42000000,0x42000000,0x10000000,0x824000,0x10000,0x3400,0x20000,0x4000,};
   }

  /** Constructor with InputStream. */
  public Dot2DotParser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Dot2DotParser(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new Dot2DotParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 24; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 24; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public Dot2DotParser(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new Dot2DotParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 24; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 24; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public Dot2DotParser(Dot2DotParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 24; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(Dot2DotParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 24; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[31];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 24; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 31; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
