/* Generated By:JavaCC: Do not edit this line. Dot2DotParserTreeConstants.java Version 5.0 */
package mieic.comp.parser;

public interface Dot2DotParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTGRAPH = 2;
  public int JJTDIGRAPH = 3;
  public int JJTATTRSTMT = 4;
  public int JJTEDGESTMT = 5;
  public int JJTASSIGNSTMT = 6;
  public int JJTNODESTMT = 7;
  public int JJTSUBGRAPH = 8;
  public int JJTATTRIBUTE = 9;
  public int JJTEDGEREL = 10;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Graph",
    "Digraph",
    "AttrStmt",
    "EdgeStmt",
    "AssignStmt",
    "NodeStmt",
    "Subgraph",
    "Attribute",
    "EdgeRel",
  };
}
/* JavaCC - OriginalChecksum=ce8b6bb618449a0b8f8e0e903cddf01a (do not edit this line) */
