/* Generated By:JavaCC: Do not edit this line. Dot2DotParserTreeConstants.java Version 5.0 */
package mieic.comp.parser;

public interface Dot2DotParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;


  public String[] jjtNodeName = {
    "Start",
    "void",
  };
}
/* JavaCC - OriginalChecksum=bbe996aa2e0e9388354969deddf4793b (do not edit this line) */
