/* Generated By:JJTree&JavaCC: Do not edit this line. Dot2DotParserConstants.java */
package mieic.comp.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Dot2DotParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int STRICT = 9;
  /** RegularExpression Id. */
  int GRAPH = 10;
  /** RegularExpression Id. */
  int DIGRAPH = 11;
  /** RegularExpression Id. */
  int NODE = 12;
  /** RegularExpression Id. */
  int EDGE = 13;
  /** RegularExpression Id. */
  int SUBGRAPH = 14;
  /** RegularExpression Id. */
  int DIRECTION = 15;
  /** RegularExpression Id. */
  int EDGEOP = 16;
  /** RegularExpression Id. */
  int ID = 17;
  /** RegularExpression Id. */
  int LETTER = 18;
  /** RegularExpression Id. */
  int DIGIT = 19;
  /** RegularExpression Id. */
  int NUMERAL = 20;
  /** RegularExpression Id. */
  int STRING = 21;
  /** RegularExpression Id. */
  int HTML = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<token of kind 3>",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 6>",
    "<token of kind 7>",
    "<token of kind 8>",
    "<STRICT>",
    "<GRAPH>",
    "<DIGRAPH>",
    "<NODE>",
    "<EDGE>",
    "<SUBGRAPH>",
    "<DIRECTION>",
    "<EDGEOP>",
    "<ID>",
    "<LETTER>",
    "<DIGIT>",
    "<NUMERAL>",
    "<STRING>",
    "<HTML>",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"=\"",
    "\":\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
  };

}
